language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1
solution: Bot/YogRobot.Bot.sln
services:
  - mongodb
script: ./build.sh
deploy:
  provider: releases
  api_key: $GitHubReleasesKey
  file:
    - YogRobot.Bot.zip
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
# git commit -m ""
# git tag version
# git push --tags
# git push
