language: csharp
dist: focal
sudo: required
mono: none
dotnet: 3.1
solution: Jottai.Agent.sln
services:
  - mongodb
script: ./build.sh
deploy:
  provider: releases
  api_key: $GitHubReleasesKey
  file:
    - jottai.agent.zip
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
# git commit -m ""
# git tag version
# git push --tags
# git push
