namespace Jottai

module Fake = 
    open Microsoft.FSharp.Data.UnitSystems.SI.UnitSymbols
    
    let private ExampleMeasurement = Measurement.Temperature 15.0<C>
    let Measurement measurement = (measurement, "ExampleDevice")
    let MeasurementFromDevice measurement deviceId = (measurement, deviceId)
    let SomeMeasurementFromDevice deviceId = (ExampleMeasurement, deviceId)
    let MeasurementWithDeviceProperty deviceProperty = (deviceProperty, "ExampleDevice")
    let DeviceId = "ExampleSensor"
    
    let DeviceData : ApiObjects.DeviceData = 
        { timestamp = ""
          gatewayId = ""
          channel = ""
          deviceId = DeviceId
          deviceName = ""
          manufacturerName = null
          data = []          
          batteryVoltage = ""
          rssi = "" }
    
    let SensorEventWithEmptyDatumValues : ApiObjects.DeviceData = 
        let data : ApiObjects.DeviceDatum list = 
          [ { propertyId = null
              propertyName = "CONTACT"
              propertyDescription = ""
              protocol = null
              propertyTypeId = null
              unitOfMeasurement = null
              value = ""
              valueType = null
              formattedValue = ""
              minimumValue = ""
              maximumValue = "" }
            { propertyId = null
              propertyName = "TEMPERATURE"
              propertyDescription = ""
              protocol = null
              propertyTypeId = null
              unitOfMeasurement = null
              value = null
              valueType = null
              formattedValue = ""
              minimumValue = ""
              maximumValue = "" }
            { propertyId = null
              propertyName = "TEMPERATURE"
              propertyDescription = ""
              unitOfMeasurement = null
              value = ""
              valueType = null
              formattedValue = ""
              minimumValue = ""
              maximumValue = ""
              protocol = null
              propertyTypeId = null } ]

        { timestamp = ""
          gatewayId = ""
          channel = ""
          deviceId = DeviceId
          deviceName = ""
          manufacturerName = ""
          data = data
          batteryVoltage = ""
          rssi = "" }
    
    let SensorEventWithInvalidDatumValues : ApiObjects.DeviceData = 
        let data : ApiObjects.DeviceDatum list = 
              [ { propertyId = null
                  propertyName = "TEMPERATURE"
                  propertyDescription = ""
                  protocol = null
                  propertyTypeId = null
                  unitOfMeasurement = null
                  value = "INVALID"
                  valueType = null
                  formattedValue = ""
                  minimumValue = ""
                  maximumValue = "" } ]
        { timestamp = ""
          gatewayId = ""
          channel = ""
          deviceId = DeviceId
          deviceName = ""
          manufacturerName = ""
          data = data
          batteryVoltage = ""
          rssi = "" }
    
    let SensorEventWithInvalidDeviceProperties : ApiObjects.DeviceData = 
        { timestamp = ""
          gatewayId = ""
          channel = ""
          deviceId = DeviceId
          deviceName = ""
          manufacturerName = ""
          data = []
          batteryVoltage = "INVALID"
          rssi = "INVALID" }
    
    let SensorEventWithUnknownDatumValues : ApiObjects.DeviceData = 
        let data : ApiObjects.DeviceDatum list =
              [ { propertyId = null
                  propertyName = ""             
                  propertyDescription = ""
                  protocol = null
                  propertyTypeId = null
                  unitOfMeasurement = null
                  value = "1"
                  valueType = null
                  formattedValue = ""
                  minimumValue = ""
                  maximumValue = "" }
                { propertyId = null
                  propertyName = null
                  propertyDescription = ""
                  protocol = null
                  propertyTypeId = null
                  unitOfMeasurement = null
                  value = "2"
                  valueType = null
                  formattedValue = ""
                  minimumValue = ""
                  maximumValue = "" }
                { propertyId = null
                  propertyName = "SOMETHING"
                  propertyDescription = ""
                  protocol = null
                  propertyTypeId = null
                  unitOfMeasurement = null
                  value = "2"
                  valueType = null
                  formattedValue = ""
                  minimumValue = ""
                  maximumValue = "" } ]

        { timestamp = ""
          gatewayId = ""
          channel = ""
          deviceId = DeviceId
          deviceName = ""
          manufacturerName = ""
          data = data
          batteryVoltage = ""
          rssi = "" }

    let ZWavePlusDevicePropertyDatum : ApiObjects.DeviceDatum =
            { propertyId = "0x0002000001dc8013"
              propertyName = "Example device part"
              propertyDescription = "Example device part description"
              protocol = "Z-Wave Plus"
              propertyTypeId = "37"
              unitOfMeasurement = null
              value = "True"
              valueType = "bool"
              formattedValue = "True"
              minimumValue = "0"
              maximumValue = "0"
              }